export const products = localStorage.getItem("cart")
  ? JSON.parse(localStorage.getItem("cart"))
  : [
      {
        id: 1,
        image: "./img/1.png",
        title: "Вариативный замок Golden Soft для отеля",
        price: 7000,
        realPrice: "9 000₽",
        categories: ["Популярности", "summer"],
        rating: "20",
        description: "nimadir nimadir",
        elCart: false,
      },
      {
        id: 2,
        image: "./img/2.png",
        title: "Дверной Замок Golden Soft для офиса",
        price: 33000,
        realPrice: "39 000₽",
        categories: ["popular", "summer"],
        rating: "20",
        description: "nimadir nimadir",
        elCart: false,
      },
      {
        id: 3,
        image: "./img/3.png",
        title: "Дверной Замок Golden Soft для офиса",
        price: 9000,
        realPrice: "12000₽",
        categories: ["popular", "summer"],
        rating: "20",
        description: "nimadir nimadir",
        elCart: false,
      },

      {
        id: 4,
        image: "./img/1.png",
        title: "Вариативный замок Golden Soft для отеля",
        price: 7000,
        realPrice: "9 000₽",
        categories: ["test", "summer"],
        rating: "20",
        description: "nimadir nimadir",
        elCart: false,
      },
      {
        id: 5,
        image: "./img/2.png",
        title: "Дверной Замок Golden Soft для офиса",
        price: 33000,
        realPrice: "39 000₽",
        categories: ["popular", "summer"],
        rating: "20",
        description: "nimadir nimadir",
        elCart: false,
      },
      {
        id: 6,
        image: "./img/3.png",
        title: "Дверной Замок Golden Soft для офиса",
        price: 9000,
        realPrice: "12000₽",
        categories: ["test", "summer"],
        rating: "20",
        description: "nimadir nimadir",
        elCart: false,
      },

      {
        id: 7,
        image: "./img/1.png",
        title: "Вариативный замок Golden Soft для отеля",
        price: 7000,
        realPrice: "9 000₽",
        categories: "test",
        rating: "20",
        description: "nimadir nimadir",
        elCart: false,
      },
      {
        id: 8,
        image: "./img/2.png",
        title: "Дверной Замок Golden Soft для офиса",
        price: 33000,
        realPrice: "39 000₽",
        categories: ["popular", "Популярности"],
        rating: "20",
        description: "nimadir nimadir",
        elCart: false,
      },
      {
        id: 9,
        image: "./img/3.png",
        title: "Дверной Замок Golden Soft для офиса",
        price: 9000,
        realPrice: "12000₽",
        categories: ["test", "summer"],
        rating: "20",
        description: "nimadir nimadir",
        elCart: false,
      },
    ];
